name: ENDF-VIII Data
on:  
  push:    
    branches:
    - main
  pull_request:    
    branches:
    - main

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Readme
        run: python readme_writer.py
      - name: Build
        run: |
            docker build --tag nuc_data_maker .
            rm -rf h5_files
            docker run -v /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}:/share nuc_data_maker /bin/bash -c "python data/generate_endf.py -d /share/h5_files --temperatures 550 600"
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add h5_files/*.h5
          git add h5_files/cross_sections.xml
          git add README.md
          git commit -m "Added readme with repo name (bot commit)" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
